apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "$repo-name$.fullname" . }}
  labels:
    {{- include "$repo-name$.labels" . | nindent 4 }}
data:
  HTTP_SERVER_PORT: {{ .Values.container.configuration.httpServerPort | quote}}
  POD_NAMESPACE: {{ .Release.Namespace }}
