apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "poc-conflate.fullname" . }}
  labels:
    {{- include "poc-conflate.labels" . | nindent 4 }}
data:
  HTTP_SERVER_PORT: {{ .Values.container.configuration.httpServerPort | quote}}
  HTTP_SERVER_PORT_TEST_CONTAINER: "8081"
  POD_NAMESPACE: {{ .Release.Namespace }}
  KAFKA_BOOTSTRAP_SERVERS: {{ include "poc-conflate.kafkaBootstrapServers" . }}
  EXCHANGE_TOPIC: "exchange.outbound"
  EV_TOPIC: "rtt.inbound.mappings"