apiVersion: v1
kind: Service
metadata:
  name: {{ include "$repo-name$.fullname" . }}
  labels:
    {{- include "$repo-name$.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "$repo-name$.selectorLabels" . | nindent 4 }}
