#This is the jobs to be executed when a Release is created from workflows
name: Create Release

on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Name of the release branch'
        required: true
      reason:
        description: 'Reason for release'
        required: true

env:
  GITHUB_TOKEN: \${{ github.token }}
  ORG_TOKEN: \${{ secrets.SVC_TS_JENKINS_GIT_SPORTSBET_ORG_TOKEN }}
  DOCKER_REGISTRY: "ghcr.io"

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'


      - name: Setup Github User And Release Branch
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b releases/\${{ github.event.inputs.branchName }}
          git push --set-upstream origin releases/\${{ github.event.inputs.branchName }}


      - name: Login to Docker in preparation for publish
        run: docker login -u flutter-global -p \${GITHUB_TOKEN} \${DOCKER_REGISTRY}/flutter-global

      - name: Release and tag version
        run: sbt "coverageOff" "release with-defaults"

      - name: Package Helm Chart
        run: helm package helm/$repo-name$ -d charts/

      - name: Index Helm Charts
        run: helm repo index charts/ --merge charts/index.yaml

      - name: Create Release PR
        run: |
          git add charts/
          git commit -am"Updating charts registry"
          git push
          hub pull-request -f -b main -m "Release \${{ github.event.inputs.branchName }}" -m "\${{ github.event.inputs.reason }}"
